columnSuffix: abnkyoym
contentColumnType: text
fieldGroup: 60c5c061-d5cc-49b3-b064-1d70c755fcb7 # ope
handle: excerpt
instructions: null
name: Excerpt
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
