fieldLayouts:
  31b35a49-564b-46dd-b837-78e9d64de44f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 347b0add-8d88-4909-a4f9-8911b758d0bb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae0729f1-a942-436d-9a33-57af79e48d50 # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d209934-e306-443a-9f74-4cedc4129b62
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bc27fe47-7b6f-46a5-b5fb-bf40b2735ced # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2169b47c-fb31-4c56-a857-dd7ef46ee19f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 52560af9-c47b-4b6d-a810-d4755e1c9071
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: fb2deed1-17d0-441b-b967-de476de2c9d2 # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
