dateModified: 1681154262
email:
  fromEmail: andrew@nystudio107.com
  fromName: Craft
  transportType: craft\mail\transportadapters\Sendmail
fs:
  site:
    hasUrls: true
    name: Site
    settings:
      path: '@webroot/assets/site'
    type: craft\fs\Local
    url: '@assetsUrl/assets/site'
meta:
  __names__:
    5c642d7e-b16b-4836-9575-668d75d242e5: Site # Site
    53ed4ec6-af5c-42a2-afad-80c9a997d531: 'Public Schema' # Public Schema
    60c5c061-d5cc-49b3-b064-1d70c755fcb7: ope # ope
    ae0729f1-a942-436d-9a33-57af79e48d50: Excerpt # Excerpt
    bc27fe47-7b6f-46a5-b5fb-bf40b2735ced: Body # Body
    d44c7c91-4980-4e50-a4a5-9dea05759752: Default # Default
    fb2deed1-17d0-441b-b967-de476de2c9d2: News # News
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Craft Starter Vite'
  retryDuration: 60
  schemaVersion: 4.4.0.4
  timeZone: America/New_York
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
